name: Run on new files in folder

on:
  push:
    paths:
      - 27jan/**

jobs:
  new-files-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch the last two commits

      - name: Check for new files
        id: check_files
        run: |
          git diff --name-only HEAD^ HEAD | grep '^27jan/' || exit 1

      - name: Run your script
        if: success()
        run: echo "New files have been added to my-folder"
