name: Run on new files in folder

on:
  push:
    paths:
      - my-folder/**

jobs:
  new-files-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for new files
        id: check_files
        run: |
          git fetch origin
          git diff --name-only origin/main...HEAD | grep '^my-folder/' || exit 1

      - name: Run your script
        if: success()
        run: echo "New files have been added to my-folder"
